### ISSUE TITLE
Support for KernelAbstractions v0.6 / CUDA v3?

### ISSUE THREAD

**Issue by navidcy** [mcabbott/Tullio.jl#102]
I was wondering about plans to release a version that supports KernelAbstractions v0.6 / CUDA v3. These seem required to bump to julia v1.6. 

(Eg see discussion at https://github.com/CliMA/Oceananigans.jl/pull/1514)

**Comment by mcabbott** [comment]
Since Tullio doesn't depend on these packages (and just writes code which needs them in the caller's scope) I think the versions in Project.toml may not matter -- they constrain what's installed when testing this package, but I don't think they constrain what it can be used with. But I could be wrong about that!

It would still be good to test on the latest. I fiddled a bit in #79 and think the only change was to load CUDAKernels: https://github.com/mcabbott/Tullio.jl/pull/79/files#diff-2e0b8b4f687f1eb1bf7d0c6f22c00e3acaddefc4f03c54a593ce53918e63441b . But perhaps this should be done separately since #79 has other problems.

**Comment by mcabbott** [comment]
It looks like CODA@3 needs CUDAKernels@0.2, which exists but isn't tagged yet?

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/lib/CUDAKernels/Project.toml

https://github.com/JuliaRegistries/General/pulls?q=is%3Apr+CUDAKernels

It also needs Julia@1.6, which https://github.com/mcabbott/Tullio.jl/pull/103/commits/b0d83e19a59f207209444e35c1c055b29d4bb110 adds to the GPU testing.

**Comment by navidcy** [comment]
Yeap, you are right. I’ll check with them about tagging CUDAKernels.
