### ISSUE TITLE
StructArrays timing 

### ISSUE THREAD

**Issue by AshtonSBradley** [mcabbott/Tullio.jl#119]
This could be overly simplistic, but I tried using StructArrays for complex and was surprised to not see any speedup:

```
using LoopVectorization, StructArrays, Tullio
using BenchmarkTools
##
n = 1000
a = StructArray(randn(n,n)+im*randn(n,n))
b = StructArray(randn(n,n)+im*randn(n,n))
c = StructArray(randn(n,n)+im*randn(n,n))

##
@btime @tullio c.re[i,j] = a.re[i,q]*b.re[q,j];
205.388 ms (77 allocations: 3.03 KiB)

##
A = randn(n,n) 
B = randn(n,n) 
C = randn(n,n) 

##
@btime @tullio C[i,j] = A[i,q]*B[q,j];
12.438 ms (62 allocations: 2.41 KiB)
```
I had the impression that `StructArrays` converts into two real arrays so that maybe `Tullio` could use `LoopVectorization` for this? I would expect to see similar timing for the real parts as for regular real arrays. What am I missing here?

**Comment by chriselrod** [comment]
```julia
julia> cre = c.re; are = a.re; bre = b.re;

julia> @btime @tullio $c.re[i,j] = $a.re[i,q]*$b.re[q,j];
  27.895 ms (530 allocations: 28.98 KiB)

julia> @btime @tullio $cre[i,j] = $are[i,q]*$bre[q,j];
  1.696 ms (533 allocations: 27.56 KiB)
```
The problem isn't with `StructArrays`, but seems to be with `Tullio`, burrowed inside `@macroexpand @tullio c.re[i,j] = a.re[i,q]*b.re[q,j]`, I see:
```julia
(Tullio.threader)(𝒜𝒸𝓉!, (Tullio.storage_type)(c.re, a, b), c.re, tuple(a, b), tuple(𝒶𝓍i, 𝒶𝓍j), tuple(𝒶𝓍q), +, 262144, nothing)
```
Note, specifically
```julia
(Tullio.storage_type)(c.re, a, b)
```
Which yields
```julia
julia> (Tullio.storage_type)(c.re, a, b)
AbstractMatrix (alias for AbstractArray{T, 2} where T)

julia> (Tullio.storage_type)(c.re, a.re, b.re)
Matrix{Float64} (alias for Array{Float64, 2})
```
So we get `AbstractMatrix` instead of `Matrix{Float64}`.
The `LoopVectorization` function that `Tullio` defines requires:
```julia
local function 𝒜𝒸𝓉!(::Type{<:Array{<:Union{Base.HWReal, Bool}}}, ℛ::AbstractArray{𝒯}, a, b, 𝒶𝓍i, 𝒶𝓍j, 𝒶𝓍q, ♻️ = nothing, 💀 = true) where 𝒯
```
That is, it requires an array typed with `<:Union{Base.HWReal,Bool}`. But instead, our `storage_type` is `AbstractMatrix`.

I assume Tullio should be calling `(Tullio.storage_type)(c.re, a.re, b.re)` instead of `(Tullio.storage_type)(c.re, a, b)`

**Comment by AshtonSBradley** [comment]
oh nice, looks like I can just relabel in 2d. I realized after I posted this that it may not help much as what I want is to do this in 3d. Do you know of a StructArrays equivalent that works in higher dimensions?

**Comment by chriselrod** [comment]
What're you trying to do?
Things like:
```julia
A = rand(Complex{Float64}, 3, 4, 5);
Are = reinterpret(reshape, Float64, A)
```
Should be fine.

**Comment by mcabbott** [comment]
> Tullio should be calling `(Tullio.storage_type)(c.re, a.re, b.re)` instead

Yes, that's completely right. I'd call that a bug.

I suspect it should actually pull out field access completely, which would also solve #96. It does this already for functions: since it doesn't know `real(a)` is cheap, it does it once up front, and the local `var"real(a)"` then works like `A` of course:
```
julia> @btime @tullio c.re[i,j] = a.re[i,q]*b.re[q,j];
  149.374 ms (77 allocations: 3.31 KiB)

julia> @btime @tullio c.re[i,j] = real(a)[i,q] * real(b)[q,j];
  19.254 ms (77 allocations: 15.26 MiB)
```

**Comment by AshtonSBradley** [comment]
So for now it's ok to use real(a) with structarrays?

**Comment by mcabbott** [comment]
Yes, and should remain OK. 

Well, I notice my example only does this on the right, the left hand side has (for some reason) slightly different parsing: there is a chance it may not work there, although `c.re` does.
