### ISSUE TITLE
Force avx to "avx = false" when use LHS scattering, unless the index is checked to be unique.

### ISSUE THREAD

**Issue by N5N3** [mcabbott/Tullio.jl#27]
```julia
using Tullio
using LoopVectorization
J = [1,3,1,1]
A = [i^2 for i in 1:10]
```
### Example 1(wrong):
```julia
@tullio B[J[i],k] := A[k]
@tullio B[J[i],k] += A[k]
# 3×10 Array{Int64,2}:
#  1  4  9  16  25  36  49  64  81  100
#  0  0  0   0   0   0   0   0   0    0
#  1  4  9  16  25  36  49  64  81  100
```
### Example 2(right):
```julia
@tullio B[J[i],k] := A[k]
@tullio avx=false B[J[i],k] += A[k]
# 3×10 Array{Int64,2}:
#  4  16  36  64  100  144  196  256  324  400
#  0   0   0   0    0    0    0    0    0    0
#  2   8  18  32   50   72   98  128  162  200
```
As @avx can't tell the user all the misusing, maybe the default set should be avx = false.

**Comment by chriselrod** [comment]
LoopVectorization issue:
https://github.com/chriselrod/LoopVectorization.jl/issues/145

The problem there is that if you try to write to the same memory location multiple times simultaneously, the answer is going to be undefined (but probably equal to one of those simultaneous write attempts).
This could also be considered a `cumsum`-like example, in that correct value of memory-reads are also changing between loop iterations.

I'd say this is a problem in documentation. @N5N3 should've been able to figure out that this is expected behavior.

**Comment by mcabbott** [comment]
Thanks for finding this. There is some logic to prevent multi-threading from messing this up, with `+=` it sets `unsafeind = [:i]` which hides `i` from `threader`. It's possible this ought to also disable `@avx` entirely.

**Comment by N5N3** [comment]
So the SubArray ver is correct only because the size is small and the Multi-threads is not open?
