### ISSUE TITLE
Slowdown when multiple variables looped

### ISSUE THREAD

**Issue by platawiec** [mcabbott/Tullio.jl#40]
I didn't see a warning about this anywhere so I thought to open an issue. When I have multiple variables in the inner loop it takes much longer to finish, I'm assuming because it isn't contracting indices intelligently (though I could be wrong). Here is a test case where I multiply 3 matrices, maybe there is a better way to have written it within the Tullio framework:

MWE:

```julia
using BenchmarkTools
using Tullio

function mul3(A, B, C) 
    A * (B * C)
end

function mul3_tullio(A, B, C) 
    @tullio Y[i, j] := A[i, k] * B[k, l] * C[l, j]
end

A, B, C = rand(100, 100); rand(100, 100); rand(100, 100)
@btime mul3($A, $B, $C)
#   89.030 μs (4 allocations: 156.41 KiB)

@btime mul3_tullio($A, $B, $C)
#   111.093 ms (3 allocations: 78.25 KiB)

mul3(A, B, C) ≈ mul3_tullio(A, B, C)
# true
```

This is on Julia 1.4.1, Tullio version 0.2.7

**Comment by mcabbott** [comment]
Indeed this will become slow, multiplying N matrices of size L it ends up like L^(N+1), whereas doing them in sequence is like (N-1)*L^3. So you expect a factor of 50, and for Tullio to get close to that, it needs LoopVectorization:
```julia
julia> using LoopVectorization, Tullio, BenchmarkTools

julia> A, B, C = rand(100, 100), rand(100, 100), rand(100, 100);

julia> mul3(A, B, C) ≈ mul3_tullio(A, B, C)
true

julia> @btime mul3($A, $B, $C);
  88.867 μs (4 allocations: 156.41 KiB)

julia> @btime mul3_tullio($A, $B, $C);
  3.372 ms (47 allocations: 81.19 KiB)

julia> BLAS.vendor()
:openblas64
```
Whether it could do better, I have not thought hard about this. It seems like a tricky problem to recognise that the loops can be re-ordered, and I think you need somewhere to store the intermediate result (note the memory use above). Tullio doesn't really know that matrix multiplication exists, it just happens to be an outcome of blindly making loops.

But TensorOperations (almost) knows only about matrix multiplication. And, at present, Tullio will call this if it's loaded & applicable. (This is largely so that it can add gradient definitions.) Besides doing them sequentially, this caches the intermediate array, and only allocates the last one.
```julia
julia> using TensorOperations

julia> function mul3_tullio(A, B, C) 
           @tullio Y[i, j] := A[i, k] * B[k, l] * C[l, j] # tensor=true # is the default
       end;

julia> @btime mul3_tullio($A, $B, $C);
  95.656 μs (34 allocations: 79.84 KiB)
```

**Comment by platawiec** [comment]
The way you framed and implemented it makes complete sense. Are there any introspection capabilities, across either TensorOPerations or Tullio which would help illuminate under the hood? What do you typically use or look at?

**Comment by mcabbott** [comment]
If you add `verbose=2` it will print everything out. Maybe this will help too: https://gist.github.com/mcabbott/7494c8cc46a906fe88172dbfc8b92ad2

**Comment by platawiec** [comment]
Thanks, that's helpful, I saw the `verbose=2` setting but now it's up to me to understand how to trigger TensorOperations better. Thanks again!
