### ISSUE TITLE
Not sure what to do with x + a + c

### ISSUE THREAD

**Issue by freemin7** [mcabbott/Tullio.jl#43]
I tried to run the following code:
```
@tullio dP[x,y,z] -= -Diff[a+2, b+2] * Diff[c+2, d+2] * P[mod(x+a+c), mod(y+b+d), z] * P[mod(x+a),mod(y+b),z] (a in -1:1, b in -1:1, c in -1:1, d in -1:1, z in 1:3, x in 1:n, y in 1:n)
 ```

I could decompose it into:
```
V[x,y,z] = Diff[c+2,d+2] * P[mod(x+c), mod(y+d), z] (c in -1:1, d in -1:1, x in 1:n, y in 1:n, z in 1:3)
```
```
dP[x,y,z] -= Diff[a+2, b+2] * V[mod(x+a), mod(y+b), z] * P[mod(x+a), mod(y+b), z] (a in -1:1, b in -1:1, x in 1:n, y in 1:n, z in 1:3) 
```

Is there good reason why `mod(x+a+c)` not supported?

**Comment by mcabbott** [comment]
Things like `A[x+y+z]` aren't supported, because inferring the ranges from constraints among 3 variables is harder than 2, so I didn't write it. Inside `mod`, it isn't trying to infer the ranges, but at present it runs the same code just to extract the names `:x, :y, :z` of the indices inside. Shouldn't be too hard to fix, I think.

Note also that `dP[x,y,z] -= -Diff[a+2, b+2] * ...` won't work, it has to be `+= Diff[...]`.
